### ISSUE TITLE
Display Time

### ISSUE THREAD

**Issue by Jimmy062006** [BreeeZe/rpos#105]
like to create an overlay but cannot see how to do this.

I'm using type 2 and its all running fine. CCTV system does not Overlay the timestamp for digital sources.

**Comment by RogerHardiman** [comment]
Adding the overlay to the Type2 RTSP server means we need the Pi to add the overlay in the GPU. I don't kow how to do that.
If you try the Type 3 RTSP server (the one that uses gstreamer) then clock overlays are supported.
