### ISSUE TITLE
Q. Is this a suitable camera?

### ISSUE THREAD

**Issue by djaus2** [BreeeZe/rpos#119]
https://www.jaycar.com.au/raspberry-pi-8mp-camera-version-v2/p/XC9017?pos=10&queryId=a0d7c78c879722c5955166e9be4e34e8&sort=relevance

Just wanted to know before I purchase it.

And is its performance with this project Ok on a RPi 3b or is a RPi 4 needed?

Thx

**Comment by RogerHardiman** [comment]
I am using the official raspberry pi V2 camera with RPOS.

Roger
