### ISSUE TITLE
RTSP Proxy Mode doesn't work with Bosch BVMS.

### ISSUE THREAD

**Issue by noomSik** [BreeeZe/rpos#145]
Hi, I've succesfully connected RPOS in testsrc mode to Bosch BVMS, but proxy mode is not working. I've tried everything, from wowza test rtsp streams to rtsp servers hosted in the same machine as RPOS, but none work. The camera doesn't show No connection but instead displays a black image. 

Any ideas of why this is happening? All streams are H264.

**Comment by RogerHardiman** [comment]
Some VMS systems only connect to the RTSP stream if it is the same IP address RPOS.
The current proxy mode just points the VMS (like BMVS) at the RTSP stream URL and if that is a different IP it may not work.
(Milestone does not like the current Proxy Mode)

The proper way to do it is run the RTSP server on the same machine as RPOS, and have that RTSP server go and get the video from your other RTSP device.
That works great in Milestone. My BVMS licence has expired so cannot test that.
