### ISSUE TITLE
GetScopes failed, and with error msg string not xml/wsdl

### ISSUE THREAD

**Issue by BlueT** [BreeeZe/rpos#16]
I'm testing rpos with node-onvif module https://github.com/agsh/onvif
Some functions works but some failed.

I found these might be 3 bugs:

1. GetScopes failed
2. HTTP 200 OK
3. Response should be wsdl, but it's returning error message string.

the following functions are OK:
/onvif/device_service:
GetCapabilities
/onvif/media_service
GetProfiles
GetVideoSources

But this Failed:
/onvif/device_service
GetScopes

The content POST to rpos:
[POST-to-RPOS.txt](https://github.com/BreeeZe/rpos/files/266888/POST-to-RPOS.txt)

The content Responed from rpos:
[Response-from-RPOS.txt](https://github.com/BreeeZe/rpos/files/266890/Response-from-RPOS.txt)

**Comment by BlueT** [comment]
![2016-05-17 04 20 08](https://cloud.githubusercontent.com/assets/51141/15302655/aaca82f0-1be6-11e6-9405-84b6b1d6837b.png)

**Comment by RogerHardiman** [comment]
I have looked at the XML sent from agsh/onvif
The XML is not valid and there is a bug in the agsh/onvif code.

It would be better if RPOS returned an XML error message rather than the error msg string.

To help out I will do a fix for agsh/onvif and a Pull Request

**Comment by RogerHardiman** [comment]
I have added a fix to agsh/onvif in this Pull Request [https://github.com/agsh/onvif/pull/37](https://github.com/agsh/onvif/pull/37)

**Comment by BlueT** [comment]
update PR link https://github.com/agsh/onvif/pull/38

**Comment by RogerHardiman** [comment]
This can be closed now.
The problem was in the agsh ONVIF library and not in RPOS.

**Comment by BlueT** [comment]
Thanks for help. :-)
