### ISSUE TITLE
Can I use this to turn a remote rtsp stream into an onvif stream?

### ISSUE THREAD

**Issue by latel** [BreeeZe/rpos#175]
I’ve done extensive research, and this project seems to be the closest match for my requirements. However, it currently only supports streaming from Raspberry Pi local cameras or local video files.

Is it possible to stream from a remote RTSP source and convert it into an ONVIF stream? My viewer only supports ONVIF-compatible cameras.

From the README, it appears that this might be feasible:
> Can reference other RTSP servers, which in turn can pull in the video via RTSP, other ONVIF sources, Desktop Capture, MJPEG allowing RPOS to be a Video Stream Proxy

However, the `RTSPAddress` configuration seems to be the RTSP address intended for viewers rather than the source RTSP address. Additionally, `CameraType` doesn’t seem to have an option for a remote source.

**Comment by latel** [comment]
yes, it's possible, take following config as a sample
```
{
  "NetworkAdapters" : ["awdl0","eth0", "wlan0", "en0"],   -> will determine onvif proxy address
  "IpAddress" : "", -> anything is fine
  "ServicePort" : 18880,  -> onvif proxy port
  "Username" : "",  -> onvif proxy username
  "Password" : "",  -> onvif proxy password
  "CameraType" : "picam", -> anything is fine
  "RTSPAddress" : "10.10.10.11",  -> your remote rtsp server address
  "RTSPPort" : 9554, -> your remote rtsp server port
  "RTSPName" : "tapo_c120", -> your remote rtsp server stream path
  "MulticastEnabled"  : false,
  "RTSPServer" : 0, -> must select 0
  .........
}

```

**Comment by sbcdave** [comment]
Hi there. I have that same config. My Reolink NVR sees the camera, but it loops through ONVIF calls and never displays the stream. Are you able to help me troubleshoot this by any chance?

**Comment by latel** [comment]
NVR typically support rtsp cameras as well, there is no need to wrap it as a onvif camera.

**Comment by sbcdave** [comment]
Mine unfortunately does not. There are two options when you add a camera, IP or ONVIF. In either case you provide the IP, port, username, and password, but there is no place to specify the path portion of the URI. The NVR is able to connect to my RPOS ONVIF server, and it gets the manufacturer, model, location, ect...data, but when it gets to requesting the URI it connects to the RTSP IP:port/path, but hangs for some reason, for about 30 seconds, and then disconnects and starts over. I've tried everything I can think of to make my RPOS replicate what one of their Reolink cameras does, but I'm missing something and the Reolink NVR isn't working. Any ideas are appreciated.
