### ISSUE TITLE
rtspServer

### ISSUE THREAD

**Issue by Nagarajran** [BreeeZe/rpos#2]
i get the following message. Is it possible to publish the source code of rtspServer, I assume its a modified live555proxy. That runs fine without this message.

rtspServer: Streaming on URL "rtsp://a.a.a.a:8554/h264"

(RTSP-over-HTTP tunneling is not available.)

Also any luck with implementing login ID and password

**Comment by BreeeZe** [comment]
Hi, the source is in the cpp folder : https://github.com/BreeeZe/rpos/blob/master/cpp/rtspServer.cpp
What is you issue specifically?

About the authentication: at the moment I don't have much time to continue with this project, so maybe later :)
