### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by am549** [BreeeZe/rpos#57]
Hi

I'm having issues getting this installed. Running the latest release of Raspian and when I run the npm install from the rpos directory I get the following items logged. I'm running everything under su.

![image](https://user-images.githubusercontent.com/32960971/51264947-81d98c00-19af-11e9-9d08-7451d90fd3b8.png)

Any ideas?

**Comment by RogerHardiman** [comment]
not sure what's wrong.
I can see Permisison Denied errors in the screenshot.

I don't built it as root.
I just build it as a normal user.

**Comment by am549** [comment]
Looks like a reboot and an install as normal user has fixed it. Was getting similar issues logged in as the default user before rebooting

**Comment by RogerHardiman** [comment]
Hi
Last time I did a fresh install I had a feeling the SerialPort module failed first time, but worked 2nd time.
But I then forgot all about it.

So maybe there is an issue there - but I don't fancy making a clean install to test with.

Anyway glad you got it working
