### ISSUE TITLE
Can only watch 2 seconds of video

### ISSUE THREAD

**Issue by fanxin2017** [BreeeZe/rpos#65]
Successful installation to the Raspberry Pi but only about 2 seconds of video can be seen through ONVIF, there will be "NO SIGNAL", I don't know where there is a problem, this is Google Translate, I hope you can understand my meaning

**Comment by RogerHardiman** [comment]
Question 1 - Which CCTV viewing software are you using?
Question 2 - in the file called rposConfig.json did you change the RTSPServer from '1' to '2'

**Comment by fanxin2017** [comment]
Ok, I didn't modify the RTSPServer。thank you.
