### ISSUE TITLE
Fix for incorrect SOAP envelope - causes ONVIF Device Manager to fail

### ISSUE THREAD

**Issue by RogerHardiman** [BreeeZe/rpos#7]
Hi there
I'm new to NodeJS but have lots of ONVIF experience.

I tried rpos with ONVIF Device Manager on Windows
ONVIF Device Manager reports a SOAP error with a mis-match between SOAP2003 and SOAP2001 envelopes.

The workaround is to edit rpos/node_modules/soap/lib/server.js and to make this one line change

```javascript
//  "<soap:Envelope xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\" " +
    "<soap:Envelope xmlns:soap=\"http://www.w3.org/2003/05/soap-envelope\" " +

```

This lets ONVIF Device Manager receive SOAP messages.
There are still problems with the ONVIF messages but this fixes the first problem.

Roger

**Comment by BreeeZe** [comment]
merged you pull request to the node-soap fork.
#https://github.com/BreeeZe/node-soap/pull/1
