### ISSUE TITLE
RTSP-over-HTTP tunneling is not available

### ISSUE THREAD

**Issue by jratha** [BreeeZe/rpos#75]
Hi all

finally got everything on my pi installed, but when i try running the server i get this. has anyone got any ideas as to what ive done wrong?

> pi@CCTV:~/rpos $ node rpos.js
Read IP address 192.168.0.8 from wlan0
Manufacturer : RPOS Raspberry Pi
Model : Model_PiZeroW_Revision_1.1
HardwareId :
SerialNumber : 00000000234e8654
FirmwareVersion : 2.0.4
Starting camera settings webserver on http://192.168.0.8:8081/
Binding DeviceService to http://192.168.0.8:8081/onvif/device_service
Binding MediaService to http://192.168.0.8:8081/onvif/media_service
Binding PTZService to http://192.168.0.8:8081/onvif/ptz_service
Binding ImagingService to http://192.168.0.8:8081/onvif/imaging_service
discovery_service started
imaging_service started
ptz_service started
device_service started
Starting Live555 rtsp server
media_service started
rtspServer: Streaming on URL "rtsp://192.168.0.8:8554/h264"

(RTSP-over-HTTP tunneling is not available.)

**Comment by a-camacho** [comment]
Same here

**Comment by Qurdobela** [comment]
Qurdo is back
